[package]
name = "cutils-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hello"
path = "src/bin/hello.rs"

[[bin]]
name = "wdt"
path = "src/bin/wdt.rs"


[dependencies]
colored = "2.*.*"
clap = { version = "4.*.*", features = ["derive"] }
